version: "3.8"
services:
  pgdb:
    image: postgres
    container_name: pgdb
    env_file:
      - variables-auth.env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - auth_db_network
      - auth_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres-auth -d auth-db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s


  pgadmin4-container:
    depends_on:
      - pgdb
    image: dpage/pgadmin4
    container_name: pgadmin4-container
    env_file:
      - variables-auth.env
    restart: always
    volumes:
      - pgadmin-info:/var/lib/pgadmin
    networks:
      - auth_db_network
      - io_db_network

  authserver:
    depends_on:
      pgdb:
        condition: service_healthy
    # for local developement
    image: auth-app:latest
    # if using on M1 with dockerhub image
    # image: dancodreanu/authserver:latest
    # platform: linux/arm64 
    container_name: authserver
    restart: always
    env_file:
      - variables-auth.env
    networks:
      - auth_network

  pgdbio:
    image: postgres
    container_name: pgdbio
    env_file:
      - variables-io.env
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - postgres-db-io:/var/lib/postgresql/data
    networks:
      - io_db_network
      - io_network
    command: -p 5001
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -p 5001 -U postgres-io -d main-db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  ioserver: 
    depends_on:
      pgdbio:
        condition: service_healthy
    image: io-app:latest
    # if using on M1 with dockerhub image
    # image: dancodreanu/ioserver:latest
    # platform: linux/arm64 
    container_name: ioserver
    restart: always
    env_file:
      - variables-io.env
    networks:
      - io_network

  businessserver:
    # if using on M1 with dockerhub image
    # image: dancodreanu/businessserver:latest
    # platform: linux/arm64 
    image: business-app:latest
    depends_on:
      - ioserver
      - authserver
    container_name: businessserver
    restart: always
    networks:
      - auth_network
      - io_network

  kong:
    image: kong:latest
    container_name: kong_gateway
    depends_on:
      - authserver
      - businessserver
    volumes:
      - ./kong:/usr/local/kong/declarative
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "3030:8000"
      - "443:8443"
    networks:
      - auth_db_network
      - auth_network
      - io_db_network
      - io_network

  portainer:
    image: portainer/portainer-ce:2.11.1
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
    restart: always
    networks:
      - auth_network
      - io_network

volumes:
  postgres-db:
    name: auth-server_postgres-db
    external: true
  pgadmin-info:
    name: auth-server_pgadmin-info
    external: true
  postgres-db-io:
    name: io-service_postgres-db-io
    external: true
  pgadmin-info-io:
    name: io-service_pgadmin-info-io
    external: true
  kong:
    name: kong
  portainer_data:
    name: portainer_data

networks:
  auth_db_network:
  auth_network:
  io_db_network:
  io_network: